name: Daily Batch Job

on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run-batch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run batch script
        run: npx ts-node ./batch/index.ts
